### ISSUE TITLE
Création CRUD Générique

### ISSUE THREAD

**Issue by medaymen** [ZanzanaTeam/PDEV-TFT#2]

**Comment by medaymen** [comment]
Branche <b>T2</b>

**Comment by medaymenjendoubi** [comment]
Branche <b>T2</b> : Crud generique + classe de test pour l'entity Player 
<br> <u>-- Livrer dans la branche master </u>

<pre>
$ git push origin T2
Counting objects: 38, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (31/31), done.
Writing objects: 100% (38/38), 5.33 KiB | 0 bytes/s, done.
Total 38 (delta 8), reused 0 (delta 0)
To https://github.com/ZanzanaTeam/PDEV-TFT.git
 * [new branch]      T2 -> T2
</pre>
